# Generated by Django 5.0.1 on 2024-01-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
