# Generated by Django 5.0.1 on 2024-01-13 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_rooms', models.IntegerField()),
                ('capacity_of_people', models.IntegerField()),
                ('university_name', models.CharField(max_length=255)),
                ('university_faculty', models.CharField(max_length=255)),
                ('university_location', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_houses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='boarding_images/')),
                ('boarding_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boarding.boardinghouse')),
            ],
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='images',
            field=models.ManyToManyField(to='boarding.image'),
        ),
    ]
