# Generated by Django 5.0.1 on 2024-01-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardinghouse',
            name='images',
        ),
    ]
