# Generated by Django 5.0.1 on 2024-01-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0002_remove_boardinghouse_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
