# Generated by Django 5.0.1 on 2024-01-13 18:57

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=authentication.models.default_profile_image, null=True, upload_to='profile_images/'),
        ),
    ]
